# Generated by Django 4.0.6 on 2022-07-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile_name_userprofile_user_userprofile_uuid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
