# Generated by Django 4.0.6 on 2022-07-19 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='projects',
            name='brief',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/project_thumbnails'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
