# Generated by Django 4.0.6 on 2022-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='brief',
            field=models.TextField(max_length=500),
        ),
    ]
