# Generated by Django 4.0.6 on 2022-07-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_projects_techstack_userprofile_about_yourself_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='brief',
        ),
        migrations.AddField(
            model_name='projects',
            name='tagline',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
