# Generated by Django 4.0.6 on 2022-07-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_projects_user_alter_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
